# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ax6zYYCV_UUzG-N7YwiqAfuUvmfsmUix
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df1=pd.read_csv('/content/drive/MyDrive/C&T train dataset.csv')
dframe=pd.read_csv('/content/drive/MyDrive/C&T test dataset.csv')
df=df=pd.concat([df1,dframe],axis=1)
df

df.isna().sum()

df.dtypes

df = df.dropna()
df

df.isna().sum()

df.drop(['sno','acc_info','employment_st'],axis=1,inplace=True)
df

credit_history = df['credit_history'].values

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['purpose'] = le.fit_transform(df['purpose'])

